# These are supported funding model platforms

buy_me_a_coffee: RedBearAK
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
issuehunt: # Replace with a single IssueHunt username
ko_fi: RedBearAK
liberapay: # Replace with a single Liberapay username
open_collective: # Replace with a single Open Collective username
otechie: # Replace with a single Otechie username
patreon: # Replace with a single Patreon username
polar: # Replace with a single Polar username
thanks_dev: # Replace with u/gh/USERNAME
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
